Repository NativeScript/nativescript-angular, pull requests merged in 2018-07, with the labels that each got.

#1404 fix(location-strategy): find the correct outlet when navigating back and forward
  e2e/modal-navigation-ng/app/app.css
  e2e/modal-navigation-ng/app/app.module.ts
  e2e/modal-navigation-ng/app/app.routing.ts
  e2e/modal-navigation-ng/app/home/home.component.html
  e2e/modal-navigation-ng/app/home/home.component.ts
  e2e/modal-navigation-ng/app/layout.component.html
  e2e/modal-navigation-ng/app/layout.component.ts
  e2e/modal-navigation-ng/app/named-router.component.html
  e2e/modal-navigation-ng/app/named-router.component.ts
  e2e/modal-navigation-ng/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/screen.ts
  e2e/modal-navigation-ng/e2e/shared.e2e-spec.ts
  e2e/router-tab-view/package.json
  nativescript-angular/directives/dialogs.ts
  nativescript-angular/platform-providers.ts
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
  tests/app/tests/ns-location-strategy.ts
Labels: bug, in progress

#1419 chore: add images
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api19-Default/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api19-Default/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api19-Default/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api21-Default/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api21-Default/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api21-Default/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api22-Default/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api22-Default/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api22-Default/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api24-Default/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api24-Default/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api24-Default/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api25-Google/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api25-Google/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api25-Google/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api26-Google/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api26-Google/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api26-Google/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api27-Google/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api27-Google/tab-view-binding-second-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api27-Google/tab-view-binding-third-tab.png
  e2e/renderer/e2e/setup.ts
Labels: in progress

#1421 chore: replace angular-devkit/build-angular with ngtools/webpack
  e2e/renderer/package.json
  e2e/router/package.json
Labels: in progress

#1416 feat(test-bed): Run render fixtures in a full-page container
  nativescript-angular/testing/src/nativescript_test_component_renderer.ts
  nativescript-angular/testing/src/util.ts
  tests/app/tests/test-config.ts
  tests/e2e/const.js
  tests/e2e/helpers/image-helper.ts
  tests/e2e/lazy-load-routing.ts
  tests/e2e/multi-page-routing.ts
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/first-navigate-clear-history-lazy-load-nav-back-sceen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/first-navigate-clear-history-lazy-load-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/first-navigate-clear-history-single-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/first-navigate-lazy-load-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/first-navigate-multi-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/first-single-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/second-navigate-back-lazy-load-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/second-navigate-back-multi-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api19-Default/second-navigate-back-single-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-navigate-clear-history-lazy-load-nav-back-sceen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-navigate-clear-history-lazy-load-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-navigate-clear-history-single-page-screen_actual.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-navigate-clear-history-single-page.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-navigate-lazy-load-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-navigate-multi-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/first-single-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/second-navigate-back-lazy-load-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/second-navigate-back-multi-page-screen.png
  tests/e2e/resources/images/ngtests/Emulator-Api24-Default/second-navigate-back-single-page-screen.png
  tests/e2e/setup.ts
  tests/e2e/single-page-routing.ts
  tests/e2e/tsconfig.json
  tests/hooks/before-prepare/nativescript-dev-typescript.js
  tests/hooks/before-watch/nativescript-dev-typescript.js
  tests/karma.conf.js
  tests/package.json
  tests/tsconfig.json
Labels: in progress

#1418 fix: mark NativeScriptModule as root injector
  nativescript-angular/nativescript.module.ts
Labels: ready for test

#1434 tests: replace images
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api19-Default/tab-view-binding-first-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api19-Default/tab-view-binding-third-tab.png
  e2e/renderer/e2e/resources/images/renderer/Emulator-Api24-Default/tab-view-binding-third-tab.png
Labels: in progress

#1230 fix(forms): Changed the TextValueAccessor to apply ng-touched on blur
  nativescript-angular/forms/value-accessors/text-value-accessor.ts
Labels: in progress

#1455 chore: bump versions to official Angular 6.1
  e2e/modal-navigation-ng/package.json
  e2e/renderer/package.json
  e2e/router-tab-view/package.json
  e2e/router/package.json
  e2e/single-page/package.json
  nativescript-angular/package.json
  tests/package.json
Labels: in progress

#1344 fix(router): avoiding throw for app stability improvements
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
  nativescript-angular/trace.ts
Labels: in progress

#1451 refactor: value accessors' touched logic cleanup
  nativescript-angular/forms/value-accessors/checked-value-accessor.ts
  nativescript-angular/forms/value-accessors/time-value-accessor.ts
Labels: in progress
