Repository NativeScript/nativescript-angular, pull requests merged in 2019-04, with the labels that each got.

#1763 chore: merge release in master
  CHANGELOG.md
Labels: cla: yes, in progress

#1753 refactor: minor changes after review
  nativescript-angular/router/ns-platform-location.ts
  nativescript-angular/router/router.module.ts
Labels: cla: yes, in progress

#1728 fix(NativeScriptPlatformRef): Destroy lastModuleRef on exitEvent
  nativescript-angular/platform-common.ts
  nativescript-angular/router/page-router-outlet.ts
Labels: cla: yes, in progress

#1759 chore(tsconfig): remove path resolution for short imports (`ui/page`)
  nativescript-angular/tsconfig.json
Labels: cla: yes, new PR

#1789 docs: update contribution change log
  CONTRIBUTING.md
  merge-guidance-schema.png
  release-contribution-guide-schema-webpack.png
Labels: cla: yes, in progress, new PR

#1791 chore: add new test for #1771
  .gitignore
  e2e/config/mocha.opts
  e2e/modal-navigation-ng/app/navigation/basic.navigation.component.ts
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/screens/screen.ts
Labels: cla: yes, new PR

#1793 release: cut the 7.2.4 release
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  build-docs.sh
  e2e/config/mocha.opts
  e2e/modal-navigation-ng/app/navigation/basic.navigation.component.ts
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/screens/screen.ts
  e2e/modal-navigation-ng/package.json
  e2e/modal-navigation-ng/references.d.ts
  merge-guidance-schema.png
  nativescript-angular/directives/dialogs.ts
  nativescript-angular/package.json
  nativescript-angular/platform-common.ts
  nativescript-angular/router/ns-platform-location.ts
  nativescript-angular/router/page-router-outlet.ts
  nativescript-angular/router/router.module.ts
  nativescript-angular/tsconfig.json
  nativescript-angular/tsconfig.typedoc.json
  release-contribution-guide-schema-webpack.png
  tests/app/tests/router-module-tests.ts
Labels: cla: yes, in progress, new PR
