Repository NativeScript/nativescript-angular, pull requests merged in 2019-02, with the labels that each got.

#1721 chore: bump package versino tp 7.3.0
  nativescript-angular/package.json
Labels: in progress

#1722 chore: bump package version to 7.2.1
  nativescript-angular/package.json
Labels: in progress

#1717 fix(location-strategy): extend support for nested primary outlets
  e2e/nested-router-tab-view/app/app.component.html
  e2e/nested-router-tab-view/app/app.routing.ts
  e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.component.html
  e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.component.ts
  e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.module.ts
  e2e/nested-router-tab-view/app/login/login.component.html
  e2e/nested-router-tab-view/app/player/player-detail.component.html
  e2e/nested-router-tab-view/app/player/players.component.html
  e2e/nested-router-tab-view/app/player/players.component.ts
  e2e/nested-router-tab-view/app/team/team-detail.component.html
  e2e/nested-router-tab-view/app/team/teams.component.html
  e2e/nested-router-tab-view/e2e/custom-tabs.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/screen.ts
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/ns-route-reuse-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
  nativescript-angular/router/router-extensions.ts
  tests/app/tests/ns-location-strategy.ts
Labels: bug, in progress

#1723 fix: Router tracing does not work with webpack
  nativescript-angular/dom-adapter.ts
  nativescript-angular/platform-common.ts
  nativescript-angular/platform.ts
Labels: in progress

#1724 docs: cut the 7.2.1 release
  CHANGELOG.md
Labels: in progress

#1725 Merge release in master
  CHANGELOG.md
  e2e/nested-router-tab-view/app/app.component.html
  e2e/nested-router-tab-view/app/app.routing.ts
  e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.component.html
  e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.component.ts
  e2e/nested-router-tab-view/app/custom-tabs/custom-tabs.module.ts
  e2e/nested-router-tab-view/app/login/login.component.html
  e2e/nested-router-tab-view/app/player/player-detail.component.html
  e2e/nested-router-tab-view/app/player/players.component.html
  e2e/nested-router-tab-view/app/player/players.component.ts
  e2e/nested-router-tab-view/app/team/team-detail.component.html
  e2e/nested-router-tab-view/app/team/teams.component.html
  e2e/nested-router-tab-view/e2e/custom-tabs.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/screen.ts
  nativescript-angular/dom-adapter.ts
  nativescript-angular/platform-common.ts
  nativescript-angular/platform.ts
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/ns-route-reuse-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
  nativescript-angular/router/router-extensions.ts
  tests/app/tests/ns-location-strategy.ts
Labels: in progress

#1734 fix(list-view): add support for "defaultTemplate"
  nativescript-angular/directives/templated-items-comp.ts
  tests/app/tests/list-view-tests.ts
Labels: in progress, patch

#1729 fix(router): routing services should be provided in forRoot only
  nativescript-angular/router/router.module.ts
  tests/app/tests/router-module-tests.ts
  tests/package.json
Labels: in progress

#1741 Myankov/merge release master
  nativescript-angular/directives/templated-items-comp.ts
  tests/app/tests/list-view-tests.ts
Labels: in progress

#1742 release: cut the 7.2.2 release
  CHANGELOG.md
  nativescript-angular/package.json
Labels: in progress

#1743 chore: merge release in master
  CHANGELOG.md
  tests/package.json
Labels: in progress

#1748 fix(location-strategy): crash on going back with router-outlet after closing modal
  e2e/single-page/app/app.css
  e2e/single-page/app/app.module.ts
  e2e/single-page/app/second/modal/modal.component.html
  e2e/single-page/app/second/modal/modal.component.ts
  e2e/single-page/app/second/second.component.ts
  e2e/single-page/e2e/tests.e2e-spec.ts
  nativescript-angular/directives/dialogs.ts
  nativescript-angular/package.json
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
Labels: in progress

#1750 fix(location-strategy): crash on going back with router-outlet after closing modal
  e2e/single-page/app/app.css
  e2e/single-page/app/app.module.ts
  e2e/single-page/app/second/modal/modal.component.html
  e2e/single-page/app/second/modal/modal.component.ts
  e2e/single-page/app/second/second.component.ts
  e2e/single-page/e2e/tests.e2e-spec.ts
  nativescript-angular/directives/dialogs.ts
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
Labels: cla: yes, in progress
