Repository NativeScript/nativescript-angular, pull requests merged in 2019-05, with the labels that each got.

#1805 tests: add mochawesome reporter
  e2e/config/mocha.opts
  e2e/modal-navigation-ng/.gitignore
  e2e/modal-navigation-ng/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal-on-init.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/setup.ts
  e2e/modal-navigation-ng/package.json
  e2e/nested-router-tab-view/.gitignore
  e2e/nested-router-tab-view/e2e/custom-tabs.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/home-tabs.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/setup.ts
  e2e/nested-router-tab-view/e2e/split-view.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/tab-view.e2e-spec.ts
  e2e/nested-router-tab-view/package.json
  e2e/renderer/.gitignore
  e2e/renderer/e2e/action-bar.e2e-spec.ts
  e2e/renderer/e2e/ngfor.e2e-spec.ts
  e2e/renderer/e2e/ngforof.e2e-spec.ts
  e2e/renderer/e2e/ngif.e2e-spec.ts
  e2e/renderer/e2e/page-router-outlet.e2e-spec.ts
  e2e/renderer/e2e/setup.ts
  e2e/renderer/e2e/tab-view.e2e-spec.ts
  e2e/renderer/package.json
  e2e/router-tab-view/.gitignore
  e2e/router-tab-view/e2e/setup.ts
  e2e/router-tab-view/e2e/tab-view-navigation.e2e-spec.ts
  e2e/router-tab-view/package.json
  e2e/router/.gitignore
  e2e/router/e2e/router.e2e-spec.ts
  e2e/router/e2e/setup.ts
  e2e/router/package.json
  e2e/single-page/.gitignore
  e2e/single-page/e2e/setup.ts
  e2e/single-page/e2e/tests.e2e-spec.ts
  e2e/single-page/package.json
Labels: in progress, new PR

#1806 chore: merge release in master tests
  CHANGELOG.md
  e2e/config/mocha.opts
  e2e/modal-navigation-ng/.gitignore
  e2e/modal-navigation-ng/e2e/modal-frame.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal-layout.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal-on-init.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/modal-navigation-ng/e2e/setup.ts
  e2e/modal-navigation-ng/package.json
  e2e/nested-router-tab-view/.gitignore
  e2e/nested-router-tab-view/e2e/custom-tabs.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/home-tabs.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/setup.ts
  e2e/nested-router-tab-view/e2e/split-view.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/tab-view.e2e-spec.ts
  e2e/nested-router-tab-view/package.json
  e2e/renderer/.gitignore
  e2e/renderer/e2e/action-bar.e2e-spec.ts
  e2e/renderer/e2e/ngfor.e2e-spec.ts
  e2e/renderer/e2e/ngforof.e2e-spec.ts
  e2e/renderer/e2e/ngif.e2e-spec.ts
  e2e/renderer/e2e/page-router-outlet.e2e-spec.ts
  e2e/renderer/e2e/setup.ts
  e2e/renderer/e2e/tab-view.e2e-spec.ts
  e2e/renderer/package.json
  e2e/router-tab-view/.gitignore
  e2e/router-tab-view/e2e/setup.ts
  e2e/router-tab-view/e2e/tab-view-navigation.e2e-spec.ts
  e2e/router-tab-view/package.json
  e2e/router/.gitignore
  e2e/router/e2e/router.e2e-spec.ts
  e2e/router/e2e/setup.ts
  e2e/router/package.json
  e2e/single-page/.gitignore
  e2e/single-page/e2e/setup.ts
  e2e/single-page/e2e/tests.e2e-spec.ts
  e2e/single-page/package.json
  nativescript-angular/package.json
Labels: cla: yes, in progress, new PR

#1808 tests: replace anonymous functions
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/tab-view.e2e-spec.ts
  e2e/renderer/e2e/action-bar.e2e-spec.ts
  e2e/renderer/e2e/ngfor.e2e-spec.ts
  e2e/renderer/e2e/ngforof.e2e-spec.ts
  e2e/renderer/e2e/ngif.e2e-spec.ts
Labels: cla: yes, in progress, new PR

#1811 chore: merge release in master
  e2e/modal-navigation-ng/e2e/modal.shared.e2e-spec.ts
  e2e/nested-router-tab-view/e2e/tab-view.e2e-spec.ts
  e2e/renderer/e2e/action-bar.e2e-spec.ts
  e2e/renderer/e2e/ngfor.e2e-spec.ts
  e2e/renderer/e2e/ngforof.e2e-spec.ts
  e2e/renderer/e2e/ngif.e2e-spec.ts
  e2e/router/app/counter.service.ts
  e2e/router/app/first/first.component.ts
  e2e/router/app/second/second.component.ts
  e2e/router/e2e/router.e2e-spec.ts
  e2e/router/package.json
  nativescript-angular/router/page-router-outlet.ts
Labels: in progress, new PR

#1740 Fix/ns views not cleaned on removal
  nativescript-angular/directives/templated-items-comp.ts
  nativescript-angular/renderer.ts
  nativescript-angular/router/ns-location-strategy.ts
  nativescript-angular/router/page-router-outlet.ts
  nativescript-angular/view-util.ts
Labels: cla: yes, in progress, new PR

#1816 test: wrap buttons on second page
  e2e/router/app/second/second.component.ts
Labels: cla: yes, in progress, new PR

#1819 fix: revert recursive remove -causing crashes
  nativescript-angular/router/page-router-outlet.ts
  nativescript-angular/view-util.ts
Labels: cla: yes, new PR

#1815 chore: bump version to 7.3.0
  nativescript-angular/package.json
Labels: cla: yes, new PR

#1814 release: update 7.2.4 release change log
  CHANGELOG.md
Labels: cla: yes, new PR

#1787 fix(router): fix return value for getTransition of NSRouterLink
  nativescript-angular/router/ns-router-link.ts
  tests/app/tests/ns-router-link.ts
  tests/app/tests/test-config.ts
  tests/karma.conf.js
  tests/package.json
Labels: cla: yes, new PR, ♥ community PR

#1831 feat: migrate to Angular 8
  e2e/animation-examples/app/animation-builder.component.ts
  e2e/animation-examples/package.json
  e2e/modal-navigation-ng/app/navigation/basic.navigation.component.ts
  e2e/modal-navigation-ng/package.json
  e2e/nested-router-tab-view/app/app.component.ts
  e2e/nested-router-tab-view/package.json
  e2e/renderer/package.json
  e2e/routable-animations/package.json
  e2e/router-tab-view/app/app.component.ts
  e2e/router-tab-view/package.json
  e2e/router/package.json
  e2e/single-page/package.json
  e2e/tests-app-ng/package.json
  nativescript-angular/directives/templated-items-comp.ts
  nativescript-angular/package.json
  nativescript-angular/router/ns-empty-outlet.component.ts
  nativescript-angular/router/ns-platform-location.ts
  ng-sample/package.json
  tests/app/tests/detached-loader-tests.ts
  tests/app/tests/list-view-tests.ts
  tests/app/tests/renderer-tests.ts
  tests/app/tests/router-module-tests.ts
  tests/package.json
Labels: cla: yes

#1840 release: cut the 8.0.0 release
  CHANGELOG.md
Labels: cla: yes

#1839 chore: bump version to 8.1.0
  nativescript-angular/package.json
Labels: cla: yes
